global:
  scrape_interval: 15s


scrape_configs:
  - job_name: "api-produtos-job"
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: ["msgateway:8080","msclientes:8080","mscartoes:8080","msavaliadorcredito:8080"]
        labels:
          application: "api-produtos"