spring:
  application:
   name: msavaliadorcredito

  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest 

server:
  port: 8080

eureka:
  client:
    service-url:
        defaultZone: http://${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissoes-cartao: emissoes-cartao

management:
  endpoints:
    enabled-by-default: false
    web:
        exposure:
          include: 'health,prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true		
